### ISSUE TITLE
Build a simple binary out of this that takes an mp3 or wav file as parameter and returns the key

### ISSUE THREAD

**Issue by gobijan** [ibsh/libKeyFinder#2]
How can this be achieved? As far as I can tell this code can only be used from within a c++ application, right? 
A wrapper around this lib offering a simple cross platform api would be great.
Usage example could be:
./libkeyfinder -f test.mp3

Outputs:
"C Major"

Sorry but I am not really into c coding and couldn't figure it out myself how to do this. The osx gui client offers something like this from the command line but how can this be ported to debian, ubuntu, windows or whatever?

**Comment by trostli** [comment]
@aybe Is your CLI tool still available anywhere? Would love to check it out!

**Comment by aybe** [comment]
Sorry, I've removed the repos ...

**Comment by SonicZentropy** [comment]
I'm almost entirely finished with a JUCE-based app that wraps this lib (amongst some other things), so I can strip it and dump a cross-platform JUCE CLI tool specifically for keyfinder sometime this weekend if there's actual interest. It'll be a bit bloated size-wise since I don't really want to tediously strip a bunch of boilerplate code out of what I have now, but it won't effect running speed.

**Comment by trostli** [comment]
That sounds like it would be quite useful Dylan! thank you

**Comment by SonicZentropy** [comment]
All done:  https://github.com/SonicZentropy/ZenTermKeyFind

Works the same way the old one apparently did.  I put an already-built Windows binary under releases.  You can build for OSX/Linux if needed, instructions in my Readme.  The libKeyFinder code may not be current...I pulled it straight out of my app, which means it's the version that was current as of whenever I submitted my most recent bugfix pull req here!

It's super quick and dirty, but should work fine.  Let me know if you have problems and I'll fix em!
